// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEfModels.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyEfModels.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260921170757_AddedEpisodes")]
    partial class AddedEpisodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyEfModels.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundInformation")
                        .HasColumnType("text");

                    b.Property<string>("BroadcastTime")
                        .HasColumnType("text");

                    b.Property<string>("BroadcastWeekday")
                        .HasColumnType("text");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DroppedCount")
                        .HasColumnType("integer");

                    b.Property<string>("EndDate")
                        .HasColumnType("text");

                    b.Property<int?>("EpisodeDuration")
                        .HasColumnType("integer");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LastTenraiUpdate")
                        .HasColumnType("date");

                    b.Property<int>("ListUserCount")
                        .HasColumnType("integer");

                    b.Property<string>("MainPictureLarge")
                        .HasColumnType("text");

                    b.Property<string>("MainPictureMedium")
                        .HasColumnType("text");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MeanScore")
                        .HasColumnType("numeric");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("Nsfw")
                        .HasColumnType("text");

                    b.Property<int?>("NumberEpisodes")
                        .HasColumnType("integer");

                    b.Property<int>("OnHoldCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Pictures")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("PlanToWatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringUserCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<string>("StartSeasonSeason")
                        .HasColumnType("text");

                    b.Property<int?>("StartSeasonYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("text");

                    b.Property<string>("TitleOriginal")
                        .HasColumnType("text");

                    b.Property<string>("TitleRomanji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TitleSynonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WatchingCount")
                        .HasColumnType("integer");

                    b.Property<int>("forumTopicsCounter")
                        .HasColumnType("integer");

                    b.Property<string>("rating")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MalId")
                        .IsUnique();

                    b.HasIndex("MediaType");

                    b.HasIndex("TitleRomanji");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("AnimeId", "CharacterId")
                        .IsUnique();

                    b.ToTable("AnimeCharacters");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCharacterVoiceActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeCharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("AnimeCharacterId", "PersonId", "Language")
                        .IsUnique();

                    b.ToTable("AnimeCharacterVoiceActors");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("AnimeCompanies");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aired")
                        .HasColumnType("text");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Filler")
                        .HasColumnType("boolean");

                    b.Property<string>("ForumUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Recap")
                        .HasColumnType("boolean");

                    b.Property<int?>("Replies")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("text");

                    b.Property<string>("TitleRomanji")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("AnimeEpisodes");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeExternalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("LinkId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Url", "AnimeId", "Name")
                        .IsUnique();

                    b.ToTable("AnimeExternalLinks");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anime1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Anime2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Anime2Id");

                    b.HasIndex("Anime1Id", "Anime2Id")
                        .IsUnique();

                    b.ToTable("AnimeRecommendations");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anime1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Anime2Id")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Anime2Id");

                    b.HasIndex("Anime1Id", "Anime2Id", "Type")
                        .IsUnique();

                    b.ToTable("AnimeRelations");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Confusing")
                        .HasColumnType("integer");

                    b.Property<int?>("Creative")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<int?>("Funny")
                        .HasColumnType("integer");

                    b.Property<int?>("Informative")
                        .HasColumnType("integer");

                    b.Property<int?>("LoveIt")
                        .HasColumnType("integer");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<int?>("Nice")
                        .HasColumnType("integer");

                    b.Property<int?>("Overall")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int?>("WellWritten")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("AnimeReviews");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("AnimeId", "PersonId", "Position")
                        .IsUnique();

                    b.ToTable("AnimeStaff");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Updated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("AnimeTheme");
                });

            modelBuilder.Entity("MyEfModels.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameKanji")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Nicknames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("MalId");

                    b.HasIndex("Name");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MyEfModels.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MyEfModels.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MyEfModels.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("AlternateNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Birthday")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer");

                    b.Property<string>("GivenName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("WebSite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MalId");

                    b.HasIndex("Name");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MyEfModels.Entities.TenraiUsageCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("TenraiUsageCounters");
                });

            modelBuilder.Entity("MyEfModels.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MalId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyEfModels.Entities.UserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("FinishDate")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRewatching")
                        .HasColumnType("boolean");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WatchedEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("UserList");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCharacter", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Character", "Character")
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCharacterVoiceActor", b =>
                {
                    b.HasOne("MyEfModels.Entities.AnimeCharacter", "AnimeCharacter")
                        .WithMany("VoiceActors")
                        .HasForeignKey("AnimeCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Person", "Person")
                        .WithMany("VoiceActingRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeCharacter");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCompany", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeCompanies")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Company", "Company")
                        .WithMany("AnimeStudios")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeEpisode", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeEpisodes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeExternalLink", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeGenre", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Genre", "Genre")
                        .WithMany("AnimeGenre")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeRecommendation", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime1")
                        .WithMany("RecommendationsFrom")
                        .HasForeignKey("Anime1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Anime", "Anime2")
                        .WithMany("RecommendationsTo")
                        .HasForeignKey("Anime2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime1");

                    b.Navigation("Anime2");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeRelation", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime1")
                        .WithMany("RelationsFrom")
                        .HasForeignKey("Anime1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Anime", "Anime2")
                        .WithMany("RelationsTo")
                        .HasForeignKey("Anime2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime1");

                    b.Navigation("Anime2");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeReview", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeReviews")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeStaff", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("Staff")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.Person", "Person")
                        .WithMany("AnimeStaffRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeTheme", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("AnimeThemes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("MyEfModels.Entities.UserList", b =>
                {
                    b.HasOne("MyEfModels.Entities.Anime", "Anime")
                        .WithMany("UserLists")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEfModels.Entities.User", "User")
                        .WithMany("UserList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEfModels.Entities.Anime", b =>
                {
                    b.Navigation("AnimeCharacters");

                    b.Navigation("AnimeCompanies");

                    b.Navigation("AnimeEpisodes");

                    b.Navigation("AnimeGenres");

                    b.Navigation("AnimeReviews");

                    b.Navigation("AnimeThemes");

                    b.Navigation("ExternalLinks");

                    b.Navigation("RecommendationsFrom");

                    b.Navigation("RecommendationsTo");

                    b.Navigation("RelationsFrom");

                    b.Navigation("RelationsTo");

                    b.Navigation("Staff");

                    b.Navigation("UserLists");
                });

            modelBuilder.Entity("MyEfModels.Entities.AnimeCharacter", b =>
                {
                    b.Navigation("VoiceActors");
                });

            modelBuilder.Entity("MyEfModels.Entities.Character", b =>
                {
                    b.Navigation("AnimeCharacters");
                });

            modelBuilder.Entity("MyEfModels.Entities.Company", b =>
                {
                    b.Navigation("AnimeStudios");
                });

            modelBuilder.Entity("MyEfModels.Entities.Genre", b =>
                {
                    b.Navigation("AnimeGenre");
                });

            modelBuilder.Entity("MyEfModels.Entities.Person", b =>
                {
                    b.Navigation("AnimeStaffRoles");

                    b.Navigation("VoiceActingRoles");
                });

            modelBuilder.Entity("MyEfModels.Entities.User", b =>
                {
                    b.Navigation("UserList");
                });
#pragma warning restore 612, 618
        }
    }
}
